### ISSUE TITLE
error message 

### ISSUE THREAD

**Issue by inhyek** [Kyeongrok/insta_crawl#1]
C:/git/python/insta_crawl/crawlerMain.py
fetching:   3%|▎         | 294/10000 [18:00<11:37:00,  4.31s/it]Failed to fetch the post: https://www.instagram.com/p/BwR2rhlH_Pk/
Traceback (most recent call last):
  File "C:\git\python\insta_crawl\inscrawler\crawler.py", line 295, in _get_posts_full
    self._fetch_post_with_key(cur_key, dict_post)
  File "C:\git\python\insta_crawl\inscrawler\crawler.py", line 195, in _fetch_post_with_key
    el_plays.text.replace(',', '').replace('.', ''))
AttributeError: 'NoneType' object has no attribute 'text'
fetching:   3%|▎         | 316/10000 [19:30<12:25:39,  4.62s/it]Failed to fetch the post: https://www.instagram.com/p/BwR1xnHncuz/

Done. Fetched 316 posts.

**Comment by Kyeongrok** [comment]
316에서 멈췄네요.

**Comment by inhyek** [comment]
네 마지막에 크롤링을 시도하던 내용은 아래와 같습니다. (긁어온 것 전체 붙여넣기하면 너무 분량이 많을까봐 마지막것을 붙여넣었어요.)

{'key': 'https://www.instagram.com/p/BwSLYn5B5R0/', 'datetime': '2019-04-15T17:08:58.000Z', 'img_urls': ['https://scontent-icn1-1.cdninstagram.com/vp/d5dba843df8c787f5b3fdc2fa4ccfa56/5D32C54B/t51.2885-15/e35/57446603_652904788480197_2224865066093196044_n.jpg?_nc_ht=scontent-icn1-1.cdninstagram.com'], 'likes': 15, 'caption': '가루스타그램
